/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 realistic_jungletree.glb 
Author: Garecra (https://sketchfab.com/Garecra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-jungletree-f187036f6de64909afc2df66035ad82f
Title: Realistic Jungletree
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const RealisticJungleTree=(props)=> {
  const { nodes, materials } = useGLTF('/realistic_jungletree.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.5}>
  <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>

          <mesh geometry={nodes.Cube071_Hawthorn_Bark_ukjjfgsdy_0.geometry} material={materials.Hawthorn_Bark_ukjjfgsdy} />
          <mesh geometry={nodes.Cube071_Hawthorn_Bark_ukjjfgsdy_0_1.geometry} material={materials.Hawthorn_Bark_ukjjfgsdy} />
          <mesh geometry={nodes.Cube071_Hawthorn_Bark_ukjjfgsdy_0_2.geometry} material={materials.Hawthorn_Bark_ukjjfgsdy} />
          <mesh geometry={nodes.Cube071_Hawthorn_Bark_ukjjfgsdy_0_3.geometry} material={materials.Hawthorn_Bark_ukjjfgsdy} />
          <mesh geometry={nodes.Cube071_Hawthorn_Bark_ukjjfgsdy_0_4.geometry} material={materials.Hawthorn_Bark_ukjjfgsdy} />
          <mesh geometry={nodes.Cube071_Hawthorn_Bark_ukjjfgsdy_0_5.geometry} material={materials.Hawthorn_Bark_ukjjfgsdy} />
          <mesh geometry={nodes.Cube071_Hawthorn_Bark_ukjjfgsdy_0_6.geometry} material={materials.Hawthorn_Bark_ukjjfgsdy} />
          <mesh geometry={nodes.Cube071_Chestnut_sefbdevh2001_0.geometry} material={materials['Chestnut_sefbdevh2.001']} />
          <mesh geometry={nodes.Cube071_Chestnut_sefbdevh2001_0_1.geometry} material={materials['Chestnut_sefbdevh2.001']} />
          <mesh geometry={nodes.Cube071_Chestnut_sefbdevh2001_0_2.geometry} material={materials['Chestnut_sefbdevh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0_1.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0_2.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0_3.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0_4.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0_5.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0_6.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0_7.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
          <mesh geometry={nodes.Cube071_Fiddle_Leaf_sdsjdgdh2001_0_8.geometry} material={materials['Fiddle_Leaf_sdsjdgdh2.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/realistic_jungletree.glb')
export default RealisticJungleTree;

